dist: trusty
language: node_js
node_js:
  - "10"

os:
  - linux
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

jobs:
  include:
    - stage: lint
      script:
        - ng lint
    - stage: build & publish showcase
      script:
        - yarn run build:showcase
      deploy:
        provider: pages:git
        cleanup: true
        token: $GH_TOKEN
        local_dir: dist/demo
        verbose: true
        edge: true
      if: branch = master
    - stage: build & publish lib
      script:
        - yarn run build:lib
        - yarn run publish:lib
      if: branch = master
